import { defineType, defineField } from 'sanity'

export default defineType({
  name: 'page',
  title: 'Seite',
  type: 'document',
  preview: {
    select: { title: 'title', slug: 'slug.current' },
    prepare({ title, slug }) {
      return {
        title: title || 'Neue Seite',
        subtitle: slug ? `/${slug}` : 'Kein Slug',
      }
    },
  },
  fields: [
    defineField({
      name: 'title',
      title: 'Seitentitel',
      type: 'string',
      validation: (Rule) => Rule.required(),
      group: 'content',
    }),
    defineField({
      name: 'slug',
      title: 'URL-Pfad (Slug)',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
      description: 'Wird als URL verwendet, z.B. /ueber-uns',
      group: 'content',
    }),
    defineField({
      name: 'seoTitle',
      title: 'SEO Titel (optional)',
      type: 'string',
      description: 'Überschreibt den Seitentitel in Suchmaschinen',
      group: 'seo',
    }),
    defineField({
      name: 'seoDescription',
      title: 'SEO Beschreibung (optional)',
      type: 'text',
      rows: 3,
      description: 'Beschreibung für Suchmaschinen (max. 160 Zeichen)',
      validation: (Rule) => Rule.max(160),
      group: 'seo',
    }),
    defineField({
      name: 'seoImage',
      title: 'SEO Bild (optional)',
      type: 'image',
      description: 'Vorschaubild für Social Media',
      group: 'seo',
    }),
    defineField({
      name: 'canonicalUrl',
      title: 'Canonical URL (optional)',
      type: 'url',
      description: 'Falls die Seite unter einer anderen URL erreichbar ist (Duplicate Content vermeiden)',
      group: 'seo',
    }),
    defineField({
      name: 'noIndex',
      title: 'Seite von Suchmaschinen ausschließen',
      type: 'boolean',
      description: 'Setzt noindex — Seite wird nicht in Google angezeigt',
      initialValue: false,
      group: 'seo',
    }),
    defineField({
      name: 'sitemapPriority',
      title: 'Sitemap-Priorität',
      type: 'number',
      description: '0.0 bis 1.0 — Leer = Standard aus SEO-Einstellungen. Startseite sollte 1.0 sein.',
      validation: (Rule) => Rule.min(0).max(1),
      group: 'seo',
    }),
    defineField({
      name: 'sitemapFrequency',
      title: 'Sitemap-Änderungshäufigkeit',
      type: 'string',
      options: {
        list: [
          { title: 'Standard (aus Einstellungen)', value: '' },
          { title: 'Immer', value: 'always' },
          { title: 'Stündlich', value: 'hourly' },
          { title: 'Täglich', value: 'daily' },
          { title: 'Wöchentlich', value: 'weekly' },
          { title: 'Monatlich', value: 'monthly' },
          { title: 'Jährlich', value: 'yearly' },
          { title: 'Nie', value: 'never' },
        ],
      },
      group: 'seo',
    }),
    defineField({
      name: 'excludeFromSitemap',
      title: 'Von Sitemap ausschließen',
      type: 'boolean',
      description: 'Seite wird nicht in der sitemap.xml aufgeführt',
      initialValue: false,
      group: 'seo',
    }),

    /* ─── SCHEMA / STRUCTURED DATA ─── */
    defineField({
      name: 'schemaType',
      title: 'Schema-Typ',
      type: 'string',
      description: 'Strukturierte Daten für Google Rich Snippets. "Automatisch" erkennt FAQ-Module und erstellt das passende Schema.',
      options: {
        list: [
          { title: 'Automatisch (empfohlen)', value: 'auto' },
          { title: 'Restaurant / Lokales Geschäft', value: 'restaurant' },
          { title: 'FAQ-Seite', value: 'faq' },
          { title: 'Event / Veranstaltung', value: 'event' },
          { title: 'Artikel / Blogbeitrag', value: 'article' },
          { title: 'Produkt', value: 'product' },
          { title: 'Kein Schema', value: 'none' },
        ],
      },
      initialValue: 'auto',
      group: 'schema',
    }),
    defineField({
      name: 'schemaRestaurant',
      title: 'Restaurant-Daten',
      type: 'object',
      group: 'schema',
      hidden: ({ parent }) => parent?.schemaType !== 'restaurant',
      fields: [
        defineField({ name: 'name', title: 'Name', type: 'string', initialValue: 'Mein Unternehmen' }),
        defineField({ name: 'description', title: 'Beschreibung', type: 'text', rows: 2 }),
        defineField({ name: 'cuisine', title: 'Küche', type: 'string', initialValue: 'German' }),
        defineField({ name: 'priceRange', title: 'Preisklasse', type: 'string', description: 'z.B. €€ oder €€€', initialValue: '€€€' }),
        defineField({ name: 'phone', title: 'Telefon', type: 'string', initialValue: '+49123456789' }),
        defineField({ name: 'email', title: 'E-Mail', type: 'string', initialValue: 'info@example.com' }),
        defineField({ name: 'street', title: 'Straße', type: 'string', initialValue: 'Musterstraße 1' }),
        defineField({ name: 'city', title: 'Stadt', type: 'string', initialValue: 'Musterstadt' }),
        defineField({ name: 'postalCode', title: 'PLZ', type: 'string', initialValue: '12345' }),
        defineField({ name: 'country', title: 'Land', type: 'string', initialValue: 'DE' }),
      ],
    }),
    defineField({
      name: 'schemaEvent',
      title: 'Event-Daten',
      type: 'object',
      group: 'schema',
      hidden: ({ parent }) => parent?.schemaType !== 'event',
      fields: [
        defineField({ name: 'eventName', title: 'Event-Name', type: 'string' }),
        defineField({ name: 'eventDescription', title: 'Beschreibung', type: 'text', rows: 2 }),
        defineField({ name: 'startDate', title: 'Start-Datum', type: 'datetime' }),
        defineField({ name: 'endDate', title: 'End-Datum', type: 'datetime' }),
        defineField({ name: 'location', title: 'Veranstaltungsort', type: 'string', initialValue: 'Musterstraße 1, 12345 Musterstadt' }),
        defineField({ name: 'organizer', title: 'Veranstalter', type: 'string', initialValue: 'Mein Unternehmen' }),
      ],
    }),
    defineField({
      name: 'schemaArticle',
      title: 'Artikel-Daten',
      type: 'object',
      group: 'schema',
      hidden: ({ parent }) => parent?.schemaType !== 'article',
      fields: [
        defineField({ name: 'author', title: 'Autor', type: 'string' }),
        defineField({ name: 'publishDate', title: 'Veröffentlicht am', type: 'date' }),
        defineField({ name: 'modifiedDate', title: 'Zuletzt bearbeitet am', type: 'date' }),
      ],
    }),
    defineField({
      name: 'schemaProduct',
      title: 'Produkt-Daten',
      type: 'object',
      group: 'schema',
      hidden: ({ parent }) => parent?.schemaType !== 'product',
      fields: [
        defineField({ name: 'productName', title: 'Produktname', type: 'string' }),
        defineField({ name: 'productDescription', title: 'Beschreibung', type: 'text', rows: 2 }),
        defineField({ name: 'price', title: 'Preis (€)', type: 'string' }),
        defineField({ name: 'currency', title: 'Währung', type: 'string', initialValue: 'EUR' }),
        defineField({ name: 'availability', title: 'Verfügbarkeit', type: 'string', options: {
          list: [
            { title: 'Auf Lager', value: 'InStock' },
            { title: 'Nicht verfügbar', value: 'OutOfStock' },
            { title: 'Vorbestellung', value: 'PreOrder' },
          ],
        }}),
      ],
    }),
    defineField({
      name: 'customBreadcrumbs',
      title: 'Breadcrumbs anpassen (optional)',
      type: 'array',
      description: 'Leer lassen = automatisch (Startseite → Seitentitel). Manuell setzen für individuelle Pfade.',
      group: 'schema',
      of: [
        {
          type: 'object',
          name: 'breadcrumb',
          title: 'Breadcrumb',
          preview: {
            select: { title: 'label', subtitle: 'url' },
          },
          fields: [
            defineField({ name: 'label', title: 'Bezeichnung', type: 'string', validation: (Rule) => Rule.required() }),
            defineField({ name: 'url', title: 'URL', type: 'string', validation: (Rule) => Rule.required() }),
          ],
        },
      ],
    }),

    /* ─── CUSTOM CODE ─── */
    defineField({
      name: 'customCss',
      title: 'Custom CSS',
      type: 'text',
      rows: 8,
      description: 'CSS-Code der nur auf dieser Seite geladen wird (ohne <style>-Tags)',
      group: 'code',
    }),
    defineField({
      name: 'customHeadJs',
      title: 'Custom JavaScript (Head)',
      type: 'text',
      rows: 6,
      description: 'JS-Code im <head> — z.B. Tracking-Pixel, Analytics (ohne <script>-Tags)',
      group: 'code',
    }),
    defineField({
      name: 'customBodyJs',
      title: 'Custom JavaScript (Body-Ende)',
      type: 'text',
      rows: 6,
      description: 'JS-Code am Ende der Seite — z.B. Conversion-Tags (ohne <script>-Tags)',
      group: 'code',
    }),
    defineField({
      name: 'customHeadTags',
      title: 'Zusätzliche Head-Tags',
      type: 'text',
      rows: 4,
      description: 'Beliebige HTML-Tags im <head> — z.B. <meta>, <link> (mit HTML-Tags)',
      group: 'code',
    }),

    /* ─── INHALT (Module) ─── */
    defineField({
      name: 'modules',
      title: 'Seiteninhalt (Module)',
      type: 'array',
      group: 'content',
      of: [
        { type: 'module.hero' },
        { type: 'module.text' },
        { type: 'module.imageText' },
        { type: 'module.gallery' },
        { type: 'module.cta' },
        { type: 'module.divider' },
        { type: 'module.quote' },
        { type: 'module.faq' },
        { type: 'module.form' },
        { type: 'module.blogPosts' },
        { type: 'module.video' },
      ],
      description: 'Ziehe Module per Drag & Drop, um die Seite aufzubauen',
    }),
  ],
  groups: [
    { name: 'content', title: 'Inhalt', default: true },
    { name: 'seo', title: 'SEO' },
    { name: 'schema', title: 'Schema-Daten' },
    { name: 'code', title: 'Custom Code' },
  ],
})
